# Generated by Django 5.0 on 2024-04-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_subject_alter_candidate_id_answer_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
