# Generated by Django 5.0 on 2025-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_author_remove_candidate_age_candidate_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('language', models.CharField(default="o'zbek", max_length=30)),
                ('subjects', models.ManyToManyField(to='api.subject')),
            ],
        ),
    ]
