# Generated by Django 5.0 on 2025-01-06 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_one',
            new_name='correct_option',
        ),
        migrations.RemoveField(
            model_name='major',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='is_certified',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='num_of_questions',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='point',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='test',
        ),
        migrations.AddField(
            model_name='author',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='major',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_majors', to='api.subject'),
        ),
        migrations.AddField(
            model_name='major',
            name='secondary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertest',
            name='main_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_user_tests', to='api.test'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='main_test_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usertest',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.major'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='mandatory_points',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usertest',
            name='mandatory_tests',
            field=models.ManyToManyField(related_name='mandatory_user_tests', to='api.test'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='secondary_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_user_tests', to='api.test'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='secondary_test_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usertest',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.test'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.test')),
                ('user_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.usertest')),
            ],
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
