# Generated by Django 5.0 on 2025-01-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_correct_one_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AddField(
            model_name='test',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
