# Generated by Django 5.0 on 2025-01-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_major_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('finished', 'finished')], default='in_progress', max_length=30),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='mandatory_points',
            field=models.JSONField(default={'ingliz_tili': 0.0, 'matem': 0.0, 'tarix': 0.0}),
        ),
    ]
